version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/digital_code_automating"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/digital_products_orders"
    schedule:
      interval: "daily"
